version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from BigQuery

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: daily sales data per products_id
        
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST( date_date as TIMESTAMP)"
        
        tests:
          - unique:
              column_name: "(pdt_id || '_' || orders_id)"

      - name: product
        identifier: raw_gz_product
        description: stock product price per product_id
        columns:
          - name: products_id
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: shipping fee and cost per order_id

        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
